### ISSUE TITLE
core.civetweb crash is seen 0.9.0 version

### ISSUE THREAD

**Issue by ramesht77** [jupp0r/prometheus-cpp#557]
hi,
We are observing below crash of core.civetweb thread. Please suggest whats wrong here.

```
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.el7.x86_64 glibc-2.17-325.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libcurl-7.29.0-59.el7_9.1.x86_64 libgcc-4.8.5-44.el7.x86_64 libidn-1.28-4.el7.x86_64 libselinux-2.5-15.el7.x86_64 libssh2-1.8.0-4.el7.x86_64 lksctp-tools-1.0.17-2.el7.x86_64 nspr-4.32.0-1.el7_9.x86_64 nss-3.67.0-3.el7_9.x86_64 nss-softokn-freebl-3.67.0-3.el7_9.x86_64 nss-util-3.67.0-1.el7_9.x86_64 openldap-2.4.44-24.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb) bt full
#0  0x00007fe054644387 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007fe054645a78 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007fe05519e62d in __gnu_cxx::__verbose_terminate_handler ()
    at ../../../../gcc-5.4.0/libstdc++-v3/libsupc++/vterminate.cc:95
        terminating = true
        t = <optimized out>
#3  0x00007fe05519c6b6 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../../../gcc-5.4.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
No locals.
#4  0x00007fe05519c701 in std::terminate () at ../../../../gcc-5.4.0/libstdc++-v3/libsupc++/eh_terminate.cc:57
No locals.
#5  0x00007fe05519c918 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x7fe024012280,
    tinfo=0x276f380 <_ZTISt12out_of_range@@GLIBCXX_3.4>, dest=0x4d4050 <_ZNSt12out_of_rangeD1Ev@plt>)
    at ../../../../gcc-5.4.0/libstdc++-v3/libsupc++/eh_throw.cc:87
        globals = <optimized out>
#6  0x00007fe0551c401f in std::__throw_out_of_range (__s=0x17bf794 "_Map_base::at")
    at ../../../../../gcc-5.4.0/libstdc++-v3/src/c++11/functexcept.cc:90
No locals.
#7  0x0000000001582f97 in std::__detail::_Map_base<unsigned long, std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::at (this=0x7fe00c05b8f0, __k=@0x7fe02ba594e8: 17743866286618309971)
    at /usr/local/include/c++/5.4.0/bits/hashtable_policy.h:665
        __h = 0x7fe00c05b8f0
---Type <return> to continue, or q <return> to quit---
        __code = 17743866286618309971
        __n = 1
        __p = 0x0
#8  0x00000000015814fb in std::unordered_map<unsigned long, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > >::at (this=0x7fe00c05b8f0, __k=@0x7fe02ba594e8: 17743866286618309971)
    at /usr/local/include/c++/5.4.0/bits/unordered_map.h:689
No locals.
#9  0x000000000157cf09 in prometheus::Family<prometheus::Counter>::CollectMetric (this=0x7fe00c05b8b0, hash=17743866286618309971,
    metric=0x7fe00c05b090)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/core/src/family.cc:95
        collected = {
          label = {<std::_Vector_base<prometheus::ClientMetric::Label, std::allocator<prometheus::ClientMetric::Label> >> = {
              _M_impl = {<std::allocator<prometheus::ClientMetric::Label>> = {<__gnu_cxx::new_allocator<prometheus::ClientMetric::Label>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>},
          counter = {value = 0}, gauge = {value = 0}, summary = {sample_count = 0, sample_sum = 0,
            quantile = {<std::_Vector_base<prometheus::ClientMetric::Quantile, std::allocator<prometheus::ClientMetric::Quantile> >> = {
                _M_impl = {<std::allocator<prometheus::ClientMetric::Quantile>> = {<__gnu_cxx::new_allocator<prometheus::ClientMetric::Quantile>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}},
          histogram = {sample_count = 0, sample_sum = 0,
            bucket = {<std::_Vector_base<prometheus::ClientMetric::Bucket, std::allocator<prometheus::ClientMetric::Bucket> >> = {
                _M_impl = {<std::allocator<prometheus::ClientMetric::Bucket>> = {<__gnu_cxx::new_allocator<prometheus::ClientMetric::Bucket>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0,
                  _M_end_of_storage = 0x0}}, <No data fields>}}, untyped = {value = 0}, timestamp_ms = 0}
        add_label = {__collected = @0x7fe02ba595d0}
        metric_labels = @0x1581216: {_M_t = {
---Type <return> to continue, or q <return> to quit---
            _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {<No data fields>}, <No data fields>},
              _M_key_compare = {<std::binary_function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = (std::_S_black | unknown: 2106149092), _M_parent = 0xe589485590c35df8, _M_left = 0xf87d894810ec8348,
                _M_right = 0xf0458b48f0758948}, _M_node_count = 18446743892931348808}}}
#10 0x000000000157ccf7 in prometheus::Family<prometheus::Counter>::Collect (this=0x7fe00c05b8b0)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/core/src/family.cc:79
        m = @0x7fe00c05b2a8: {first = 17743866286618309971, second = {
            _M_t = {<std::_Tuple_impl<0ul, prometheus::Counter*, std::default_delete<prometheus::Counter> >> = {<std::_Tuple_impl<1ul, std::default_delete<prometheus::Counter> >> = {<std::_Head_base<1ul, std::default_delete<prometheus::Counter>, true>> = {<std::default_delete<prometheus::Counter>> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::_Head_base<0ul, prometheus::Counter*, false>> = {_M_head_impl = 0x7fe00c05b090}, <No data fields>}, <No data fields>}}}
        __for_range = @0x7fe00c05b8b8: {
          _M_h = {<std::__detail::_Hashtable_base<unsigned long, std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<false, false, true> >> = {<std::__detail::_Hash_code_base<unsigned long, std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, std::__detail::_Select1st, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false>> = {<std::__detail::_Hashtable_ebo_helper<0, std::__detail::_Select1st, true>> = {<std::__detail::_Select1st> = {<No data fields>}, <No data fields>}, <std::__detail::_Hashtable_ebo_helper<1, std::hash<unsigned long>, true>> = {<std::hash<unsigned long>> = {<std::__hash_base<unsigned long, unsigned long>> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::__detail::_Hashtable_ebo_helper<2, std::__detail::_Mod_range_hashing, true>> = {<std::__detail::_Mod_range_hashing> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::__detail::_Hashtable_ebo_helper<0, std::equal_to<unsigned long>, true>> = {<std::equal_to<unsigned long>> = {<std::binary_function<unsigned long, unsigned long, bool>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <std::__detail::_Map_base<unsigned long, std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, std::allocator<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>> = {<No data fields>}, <std::__detail::_Insert<unsigned long, std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, std::allocator<std::pair<---Type <return> to continue, or q <return> to quit---
unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, false, true>> = {<std::__detail::_Insert_base<unsigned long, std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, std::allocator<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >> = {<No data fields>}, <No data fields>}, <std::__detail::_Rehash_base<unsigned long, std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, std::allocator<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >> = {<No data fields>}, <std::__detail::_Equality<unsigned long, std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, std::allocator<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > > >, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>> = {<No data fields>}, <std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, false> > >> = {<std::__detail::_Hashtable_ebo_helper<0, std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, false> >, true>> = {<std::allocator<std::__detail::_Hash_node<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, false> >> = {<__gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, false> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, _M_buckets = 0x7fe00c07cda0, _M_bucket_count = 5, _M_before_begin = {_M_nxt = 0x7fe00c0ee570},
            _M_element_count = 3, _M_rehash_policy = {static _S_growth_factor = 2, _M_max_load_factor = 1, _M_next_resize = 5},
            _M_single_bucket = 0x0}}
        __for_begin = {<std::__detail::_Node_iterator_base<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, false>> = {_M_cur = 0x7fe00c05b2a0}, <No data fields>}
        __for_end = {<std::__detail::_Node_iterator_base<std::pair<unsigned long const, std::unique_ptr<prometheus::Counter, std::default_delete<prometheus::Counter> > >, false>> = {_M_cur = 0x0}, <No data fields>}
        lock = {_M_device = @0x7fe00c05b9d0}
        family = {name = {static npos = 18446744073709551615,
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
              _M_p = 0x7fe02400d2c0 "SM_PDUSessionSetupSucc_SNSSAI"}, _M_string_length = 29, {
---Type <return> to continue, or q <return> to quit---
              _M_local_buf = "\036", '\000' <repeats 14 times>, _M_allocated_capacity = 30}}, help = {
            static npos = 18446744073709551615,
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
              _M_p = 0x7fe02ba59590 ""}, _M_string_length = 0, {_M_local_buf = '\000' <repeats 15 times>,
              _M_allocated_capacity = 0}}, type = prometheus::Counter,
          metric = {<std::_Vector_base<prometheus::ClientMetric, std::allocator<prometheus::ClientMetric> >> = {
              _M_impl = {<std::allocator<prometheus::ClientMetric>> = {<__gnu_cxx::new_allocator<prometheus::ClientMetric>> = {<No data fields>}, <No data fields>}, _M_start = 0x7fe0240120e0, _M_finish = 0x7fe0240121f0,
                _M_end_of_storage = 0x7fe0240121f0}}, <No data fields>}}
#11 0x00000000015936ad in prometheus::(anonymous namespace)::CollectAll<std::vector<std::unique_ptr<prometheus::Family<prometheus::Counter> > > > (results=..., families=...)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/core/src/registry.cc:16
        metrics = {<std::_Vector_base<prometheus::MetricFamily, std::allocator<prometheus::MetricFamily> >> = {
            _M_impl = {<std::allocator<prometheus::MetricFamily>> = {<__gnu_cxx::new_allocator<prometheus::MetricFamily>> = {<No data fields>}, <No data fields>}, _M_start = 0x7fe02400e050, _M_finish = 0x7fe02400e0b0,
              _M_end_of_storage = 0x7fe02400e0b0}}, <No data fields>}
        collectable = @0x7fe00c049ca8: {
          _M_t = {<std::_Tuple_impl<0ul, prometheus::Family<prometheus::Counter>*, std::default_delete<prometheus::Family<prometheus::Counter> > >> = {<std::_Tuple_impl<1ul, std::default_delete<prometheus::Family<prometheus::Counter> > >> = {<std::_Head_base<1ul, std::default_delete<prometheus::Family<prometheus::Counter> >, true>> = {<std::default_delete<prometheus::Family<prometheus::Counter> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::_Head_base<0ul, prometheus::Family<prometheus::Counter>*, false>> = {_M_head_impl = 0x7fe00c05b8b0}, <No data fields>}, <No data fields>}}
        __for_range = @0x52cf8c0: {<std::_Vector_base<std::unique_ptr<prometheus::Family<prometheus::Counter>, std::default_delete<prometheus::Family<prometheus::Counter> > >, std::allocator<std::unique_ptr<prometheus::Family<prometheus::Counter>, std::default_delete<prometheus::Family<prometheus::Counter> > > > >> = {
            _M_impl = {<std::allocator<std::unique_ptr<prometheus::Family<prometheus::Counter>, std::default_delete<prometheus::Family<prometheus::Counter> > > >> = {<__gnu_cxx::new_allocator<std::unique_ptr<prometheus::Family<prometheus::Counter>, std::default_delete<prometheus::Family<prometheus::Counter> > > >> = {<No data fields>}, <No data fields>}, _M_start = 0x7fe00c0499d0,
              _M_finish = 0x7fe00c049d08, _M_end_of_storage = 0x7fe00c049dd0}}, <No data fields>}
        __for_begin = {_M_current = 0x7fe00c049ca8}
        __for_end = {_M_current = 0x7fe00c049d08}
#12 0x0000000001593477 in prometheus::Registry::Collect (this=0x52cf8b0)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/core/src/registry.cc:45
---Type <return> to continue, or q <return> to quit---
        lock = {_M_device = @0x52cf920}
        results = {<std::_Vector_base<prometheus::MetricFamily, std::allocator<prometheus::MetricFamily> >> = {
            _M_impl = {<std::allocator<prometheus::MetricFamily>> = {<__gnu_cxx::new_allocator<prometheus::MetricFamily>> = {<No data fields>}, <No data fields>}, _M_start = 0x7fe024019200, _M_finish = 0x7fe02401b420,
              _M_end_of_storage = 0x7fe02401c200}}, <No data fields>}
#13 0x00000000015cda63 in prometheus::detail::CollectMetrics (collectables=...)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/pull/src/metrics_collector.cc:18
        collectable = {<std::__shared_ptr<prometheus::Collectable, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x52cf8b0,
            _M_refcount = {_M_pi = 0x52cf8a0}}, <No data fields>}
        metrics = <unknown type in /opt/mavenir/mvrp-cu-x86-GNBCU-R_5_0_383_84_P3/bin/gnb_cu_cp_ue_conn_mgr, CU 0x7dcd200, DIE 0x7ddaf2a>
        wcollectable = @0x5220400: {<std::__weak_ptr<prometheus::Collectable, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x52cf8b0,
            _M_refcount = {_M_pi = 0x52cf8a0}}, <No data fields>}
        __for_range = @0x5223318: {<std::_Vector_base<std::weak_ptr<prometheus::Collectable>, std::allocator<std::weak_ptr<prometheus::Collectable> > >> = {
            _M_impl = {<std::allocator<std::weak_ptr<prometheus::Collectable> >> = {<__gnu_cxx::new_allocator<std::weak_ptr<prometheus::Collectable> >> = {<No data fields>}, <No data fields>}, _M_start = 0x52203f0, _M_finish = 0x5220420,
              _M_end_of_storage = 0x5220430}}, <No data fields>}
        __for_begin = {_M_current = 0x5220400}
        __for_end = {_M_current = 0x5220420}
        collected_metrics = {<std::_Vector_base<prometheus::MetricFamily, std::allocator<prometheus::MetricFamily> >> = {
            _M_impl = {<std::allocator<prometheus::MetricFamily>> = {<__gnu_cxx::new_allocator<prometheus::MetricFamily>> = {<No data fields>}, <No data fields>}, _M_start = 0x7fe024004f70, _M_finish = 0x7fe024005090,
              _M_end_of_storage = 0x7fe024005090}}, <No data fields>}
#14 0x00000000015cb10a in prometheus::detail::MetricsHandler::handleGet (this=0x5221380, conn=0x5314110)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/pull/src/handler.cc:121
        start_time_of_request = {__d = {__r = 5341532609329364}}
        metrics = {<std::_Vector_base<prometheus::MetricFamily, std::allocator<prometheus::MetricFamily> >> = {
            _M_impl = {<std::allocator<prometheus::MetricFamily>> = {<__gnu_cxx::new_allocator<prometheus::MetricFamily>> = {<No data fields>}, <No data fields>}, _M_start = 0x7fe024004f70, _M_finish = 0x7fe024005090,
              _M_end_of_storage = 0x7fe024005090}}, <No data fields>}
        serializer = {
---Type <return> to continue, or q <return> to quit---
          _M_t = {<std::_Tuple_impl<0ul, prometheus::Serializer*, std::default_delete<prometheus::Serializer> >> = {<std::_Tuple_impl<1ul, std::default_delete<prometheus::Serializer> >> = {<std::_Head_base<1ul, std::default_delete<prometheus::Serializer>, true>> = {<std::default_delete<prometheus::Serializer>> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::_Head_base<0ul, prometheus::Serializer*, false>> = {_M_head_impl = 0x0}, <No data fields>}, <No data fields>}}
        bodySize = 22938350
        stop_time_of_request = {__d = {__r = 140600781674736}}
        duration = {__r = 0}
#15 0x00000000015ce08f in CivetServer::requestHandler (conn=0x5314110, cbdata=0x5221380)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/3rdparty/civetweb/src/CivetServer.cpp:140
        request_info = 0x5314118
        me = 0x52e7090
        handler = 0x5221380
#16 0x00000000015e3bdd in handle_request (conn=0x5314110)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/3rdparty/civetweb/src/civetweb.c:14407
        ri = 0x5314118
        path = '\000' <repeats 408 times>...
        uri_len = 8
        ssl_index = 0
        is_found = 0
        is_script_resource = 1
        is_websocket_request = 0
        is_put_or_delete_request = 0
        is_callback_resource = 1
        i = 32736
        file = {stat = {size = 0, last_modified = 0, is_directory = 0, is_gzipped = 0, location = 0}, access = {fp = 0x0}}
        callback_handler = 0x15cdf80 <CivetServer::requestHandler(mg_connection*, void*)>
        handler_info = 0x5315190
        subprotocols = 0x0
        ws_connect_handler = 0x0
        ws_ready_handler = 0x0
        ws_data_handler = 0x0
---Type <return> to continue, or q <return> to quit---
        ws_close_handler = 0x0
        callback_data = 0x5221380
        auth_handler = 0x0
        auth_callback_data = 0x0
        handler_type = 0
        curtime = 1644167535
        date = '\000' <repeats 63 times>
        __func__ = "handle_request"
#17 0x00000000015e72a8 in process_new_connection (conn=0x5314110)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/3rdparty/civetweb/src/civetweb.c:18432
        ri = 0x5314118
        keep_alive = 0
        discard_len = 732277760
        ebuf = "\000\020\240\000\000\000\000\000\004\000\000\000\000\000\000\000\000\267\245+\340\177\000\000\213\322hT\340\177\000\000\260\376\377\377\377\377\377\377", '\000' <repeats 17 times>, "\020\240\000\000\000\000\000\004\000\000\000\000\000\000\000\000\267\245+\340\177\000\000\000\254\245+\340\177\000\000\362d]\001\000\000\000\000\001\000\000"
        hostend = 0x5314a18 "\002"
        reqerr = 0
        uri_type = 2
#18 0x00000000015e7b77 in worker_thread_run (conn=0x5314110)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/3rdparty/civetweb/src/civetweb.c:18837
        ctx = 0x5313880
        thread_index = 0
        tls = {is_master = 0, thread_idx = 4, user_ptr = 0x0, alpn_proto = 0x0}
        __func__ = "worker_thread_run"
#19 0x00000000015e7c7d in worker_thread (thread_func_param=0x5314110)
    at /share/build_cache/5G_Opensource/CACHE2/5g_platform/build/staging/du/x86/prometheus-cpp-master/3rdparty/civetweb/src/civetweb.c:18892
        sa = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {0 <repeats 16 times>}},
          sa_flags = 0, sa_restorer = 0x0}
#20 0x00007fe0549e3ea5 in start_thread () from /lib64/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#21 0x00007fe05470cb0d in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb)
(gdb)
```

regards,
Ramesh

**Comment by gjasny** [comment]
Hello,
please try the latest 1.0.0 release. We fixed some bugs since 0.9.0.
Thanks,
Gregor

**Comment by ramesht77** [comment]
Hi Gregor,
Thanks for your reply. Is there any known fix which has fixed the below mentioned issue?
Please suggest.
RegardsRamesh
    On Friday, February 11, 2022, 12:56:57 PM GMT+5:30, Gregor Jasny ***@***.***> wrote:  
 
 


Hello,
please try the latest 1.0.0 release. We fixed some bugs since 0.9.0.
Thanks,
Gregor

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gjasny** [comment]
There were some locking issues in the (http)exposer fixed. AFAIR #529. We also replaced the code that breaks here completely in #532.

**Comment by ramesht77** [comment]
Thanks Gregor!!!
